// ESLint flat config — the static-analysis baseline (added 2026-07-24).
//
// Before this, the only static gate was `tsc --noEmit`. That catches type errors and nothing else:
// no unused-variable signal, no React hooks-rules enforcement, no accidental `console.log` shipped
// to a route handler, no Next.js anti-patterns.
//
// ── The one design rule for this file: it must pass CLEAN on the tree that exists today ─────────
// A lint baseline that lands red is a lint baseline everyone learns to ignore, and `--max-warnings
// 0` in CI (below, in ci.yml) makes "red" mean "blocked". So the severities here are deliberately
// calibrated to the existing ~50 lib files + 46 spec files rather than copied from a starter
// template. Tightening a rule from `off`/`warn` to `error` is a normal follow-up PR — one rule at
// a time, with the cleanup in the same diff. Do NOT tighten several at once "while you're here":
// that produces a 200-file diff nobody can review, which is how a lint baseline dies.

import nextCoreWebVitals from 'eslint-config-next/core-web-vitals';
import nextTypescript from 'eslint-config-next/typescript';
import prettier from 'eslint-config-prettier';

export default [
  {
    // Never lint generated/vendored output. `.next` and `node_modules` are obvious; the others are
    // real artifacts in this repo: the Playwright report dir, and the reference HTML mock which is
    // a design fixture, not source.
    ignores: [
      '**/node_modules/**',
      '**/.next/**',
      '**/out/**',
      '**/dist/**',
      '**/build/**',
      '**/playwright-report/**',
      '**/test-results/**',
      '**/.vercel/**',
      'references/**',
      // The plugin, kit and template (public-monorepo D4). They're mirrored byte-for-byte to golden-frijoles/skills and
      // held by that repo's own gates. An edit here is a plugin release, and linting them is `foundation-lint-gate`'s job.
      'skills/**',
      'packages/sdk/dist/**',
      // Generated by `next dev`/`next build` on every run — linting it means fighting a file
      // Next.js rewrites, and its triple-slash reference is exactly the shape Next emits.
      'apps/web/next-env.d.ts',
    ],
  },

  // ── apps/web — the Next.js app ───────────────────────────────────────────────────────────────
  // `next/core-web-vitals` bundles the React, react-hooks, jsx-a11y and Next-specific plugins.
  // eslint-config-next 16 ships flat configs natively (the FlatCompat bridge it needed on 15 now throws).
  ...[...nextCoreWebVitals, ...nextTypescript].map((config) => ({
    ...config,
    files: ['apps/web/**/*.{ts,tsx}', 'packages/**/*.{ts,tsx}'],
    // ESLint runs from the monorepo ROOT but the Next app lives at apps/web. Without this,
    // `@next/next/no-html-link-for-pages` prints "Pages directory cannot be found" on every run —
    // a permanent warning that trains everyone to skim past real output.
    settings: { ...config.settings, next: { rootDir: 'apps/web' } },
  })),

  {
    files: ['apps/web/**/*.{ts,tsx}', 'packages/**/*.{ts,tsx}'],
    rules: {
      // Unused code is the single highest-value signal tsc doesn't give us. Kept at `error`, with
      // the conventional underscore escape hatch for deliberately-ignored positional args and
      // destructured omissions (`const { secret: _secret, ...safe } = row`).
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          ignoreRestSiblings: true,
        },
      ],

      // `any` is real debt but it is NOT this PR's job to pay it down — see the design rule above.
      // Warn (visible, not blocking) so new `any`s are at least noticed in review.
      '@typescript-eslint/no-explicit-any': 'warn',

      // Server-side logging is how this codebase surfaces non-fatal failures on purpose
      // (lib/telegram.ts's `console.error` on a bad token is a documented, deliberate choice).
      // So: error and warn are legitimate; a stray `console.log` is almost always debug residue.
      'no-console': ['error', { allow: ['warn', 'error', 'info'] }],

      // Guards the invariant that costs the most when it breaks: `==` against null/undefined is
      // fine and idiomatic here, every other loose comparison is a bug waiting for a type coercion.
      eqeqeq: ['error', 'always', { null: 'ignore' }],

      // Bans `catch (e) { throw e }`-shaped no-ops and unreachable code that tsc permits.
      'no-useless-catch': 'error',
      'no-unreachable': 'error',

      // Born with the Next 16 upgrade (2026-10-04): eslint-config-next 16 brings these two, and they flag four
      // `setState` calls in effects and one relative `location.assign` that predate them. Off, per the design rule
      // above — each is its own follow-up PR, the cleanup in the same diff as the switch to `error`.
      'react-hooks/set-state-in-effect': 'off',
      '@next/next/no-location-assign-relative-destination': 'off',
    },
  },

  {
    // Specs legitimately do things app code shouldn't: log progress, hold intentionally-loose
    // fixture types, and assert on shapes the API returns as `any`.
    files: ['apps/web/e2e/**/*.ts'],
    rules: {
      'no-console': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },

  // ── scripts/ — the zero-dependency Node tooling layer ────────────────────────────────────────
  // Plain ESM on Node 22+, no framework, no React. These are CLIs: `console.log` IS their output,
  // and `process.exit` is their contract. Linting them for unused vars still earns its keep.
  {
    files: ['scripts/**/*.mjs', '*.mjs'],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'module',
      globals: { process: 'readonly', console: 'readonly', Buffer: 'readonly', URL: 'readonly' },
    },
    rules: {
      'no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'no-useless-catch': 'error',
      'no-unreachable': 'error',
    },
  },

  // LAST, always. Turns off every rule that would fight Prettier over formatting, so there is
  // exactly one tool with an opinion about whitespace and `npm run lint` can never disagree with
  // `npm run format:check`.
  prettier,
];
